import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
    try {
        const { host, user, pass, to } = await req.json();

        if (!host || !user || !pass || !to) {
            return NextResponse.json({ error: "Missing required SMTP credentials or recipient email." }, { status: 400 });
        }

        // Add this temporary log
        console.log("X-RAY - Testing SMTP with:", {
            host,
            user,
            passwordLength: pass ? pass.length : 0,
            passwordPreview: pass ? pass.substring(0, 3) + "***" : "EMPTY"
        });

        // Configure the NodeMailer Transport
        const transporter = nodemailer.createTransport({
            host: host,
            port: 587, // Standard secure SMTP port
            secure: false, // true for 465, false for other ports
            auth: {
                user: user,
                pass: pass
            }
        });

        // 1. Verify the connection credentials
        await transporter.verify();

        // 2. Send the actual test email
        const info = await transporter.sendMail({
            from: `"StockEasy System" <${user}>`, // Sender address
            to: to, // The admin's email testing the connection
            subject: '✅ StockEasy SMTP Gateway - Test Successful',
            html: `
                <div style="font-family: Arial, sans-serif; max-w: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px;">
                    <h2 style="color: #10b981;">Connection Successful!</h2>
                    <p>Hello Admin,</p>
                    <p>Your SMTP gateway is correctly configured. The StockEasy platform can now successfully dispatch system alerts, OTPs, and notifications.</p>
                    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
                    <p style="font-size: 12px; color: #64748b;">This is an automated system message generated by the StockEasy SuperAdmin Portal.</p>
                </div>
            `
        });

        return NextResponse.json({ success: true, messageId: info.messageId });
    } catch (error: any) {
        console.error("SMTP Test Error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}