import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { createClient } from '@supabase/supabase-js';
import { createClient as createServerClient } from '@/app/lib/supabase-server';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

export async function POST(req: Request) {
    try {
        // --- SECURITY PERIMETER ---
        const supabase = await createServerClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

        const { data: adminProfile } = await supabaseAdmin
            .from('platform_admins')
            .select('role, is_active')
            .eq('id', user.id)
            .maybeSingle();

        if (!adminProfile || !adminProfile.is_active || adminProfile.role !== "SUPERADMIN") {
            return NextResponse.json({ error: "Forbidden: SuperAdmin clearance required." }, { status: 403 });
        }
        // -------------------------

        const { host, user: smtpUser, pass, to } = await req.json();

        if (!host || !smtpUser || !pass || !to) {
            return NextResponse.json({ error: "Missing required SMTP credentials or recipient email." }, { status: 400 });
        }

        console.log("X-RAY - Testing SMTP with:", {
            host,
            user: smtpUser,
            passwordLength: pass ? pass.length : 0,
            passwordPreview: pass ? pass.substring(0, 3) + "***" : "EMPTY"
        });

        const transporter = nodemailer.createTransport({
            host: host,
            port: 587,
            secure: false,
            auth: {
                user: smtpUser,
                pass: pass
            }
        });

        await transporter.verify();

        const info = await transporter.sendMail({
            from: `"StockEasy System" <${smtpUser}>`,
            to: to,
            subject: '✅ StockEasy SMTP Gateway - Test Successful',
            html: `
                <div style="font-family: Arial, sans-serif; max-w: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px;">
                    <h2 style="color: #10b981;">Connection Successful!</h2>
                    <p>Hello Admin,</p>
                    <p>Your SMTP gateway is correctly configured. The StockEasy platform can now successfully dispatch system alerts, OTPs, and notifications.</p>
                    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
                    <p style="font-size: 12px; color: #64748b;">This is an automated system message generated by the StockEasy SuperAdmin Portal.</p>
                </div>
            `
        });

        return NextResponse.json({ success: true, messageId: info.messageId });
    } catch (error: any) {
        console.error("SMTP Test Error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}